// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP4fKULXyRaGg9BKcC-kzaJv4R3Y5VM44',
    appId: '1:876050634325:web:32954977d99ae48f0c66dc',
    messagingSenderId: '876050634325',
    projectId: 'whatsapp-clone-1c9a0',
    authDomain: 'whatsapp-clone-1c9a0.firebaseapp.com',
    storageBucket: 'whatsapp-clone-1c9a0.firebasestorage.app',
    measurementId: 'G-S386HFEFQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA98yCR9uKoHTnDIdWIEjnc1XVgR3FDU-Q',
    appId: '1:876050634325:android:d11c264de0af9a320c66dc',
    messagingSenderId: '876050634325',
    projectId: 'whatsapp-clone-1c9a0',
    storageBucket: 'whatsapp-clone-1c9a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvFeg7swg3QOSMZHmbzyxNlzQiqNvEi9k',
    appId: '1:876050634325:ios:f95feaa17c7b1d3f0c66dc',
    messagingSenderId: '876050634325',
    projectId: 'whatsapp-clone-1c9a0',
    storageBucket: 'whatsapp-clone-1c9a0.firebasestorage.app',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvFeg7swg3QOSMZHmbzyxNlzQiqNvEi9k',
    appId: '1:876050634325:ios:f95feaa17c7b1d3f0c66dc',
    messagingSenderId: '876050634325',
    projectId: 'whatsapp-clone-1c9a0',
    storageBucket: 'whatsapp-clone-1c9a0.firebasestorage.app',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP4fKULXyRaGg9BKcC-kzaJv4R3Y5VM44',
    appId: '1:876050634325:web:240302d506068d680c66dc',
    messagingSenderId: '876050634325',
    projectId: 'whatsapp-clone-1c9a0',
    authDomain: 'whatsapp-clone-1c9a0.firebaseapp.com',
    storageBucket: 'whatsapp-clone-1c9a0.firebasestorage.app',
    measurementId: 'G-V12QX5KDFF',
  );
}
